### install packages
install.packages("dataverse")
install.packages("causaldata")
install.packages("tidyverse")
install.packages("data.table")
install.packages("estimatr")
install.packages("evaluate")
install.packages("fixest")
install.packages("haven")
install.packages("magrittr")
install.packages("modelsummary")
install.packages("openssl")
install.packages("ragg")
install.packages("this.path")
install.packages("tinytable")
install.packages("xfun")
install.packages("quarto")