---
title: "Output of Diff-in-Diff-Replication"
format: html
---

```{r}
#| label: setup
#| include: false
#| echo: false


packs <- c('knitr', 'tidyverse', 'tinytable', 'modelsummary', 'this.path')
success <- suppressWarnings(sapply(packs, require, character.only = TRUE))
install.packages(names(success)[!success])
sapply(names(success)[!success], require, character.only = TRUE)

# set options
options(modelsummary_format_numeric_latex = "plain")
options(tinytable_latex_placement = "H")


# Note current script location
current_script_dir <- this.path::this.dir()
cat("Script directory:", current_script_dir, "\n")

# Set project root 
project_root <- this.path::dirname2(current_script_dir)
opts_knit$set(root.dir = project_root)
cat("Project root set to:", getwd(), "\n")


```

```{r}
#| label: prepare-table-1
#| include: false


# Source local code
source(file.path(project_root, "02_analysis/02_descriptives.R"))

```

## Table 1 in the paper:

This gives you @tbl-one.

```{r}
#| label: tbl-one 
#| tbl-cap: Descriptive statistics by treatment 
#| echo: false
#| message: false
#| warning: false
#| tbl-pos: H

tab_1 |>
  setNames(c("Variables", "Full Sample", 
             "Diesel Euro 4",
             "Diesel Euro 5",
             "Petrol Euro 4",
             "Petrol Euro 5")) |>
style_tt(i = 6, line = "t") |>
  style_tt(i = 8, line = "t") |>
  style_tt(i = 12, line = "t") |>
  style_tt(i = 18, line = "t")
  
```

```{r}
#| label: generate_nobs
#| include: false
#| echo: false
#| message: false
#| warning: false

# load data
# load(file.path(project_root, "01_data/processed/data.Rdata"))

## generate important variable for obs in the data.

n_carinfo <- data |> summarise(total = sum(!is.na( groups))) |> pull()
n_all <- nrow(data)
```

In sum, there are `r n_all` respondents but car info in these 4 groups is only available for `r n_carinfo`, which is 
`r sprintf( (n_carinfo/n_all)*100, fmt = '%.1f')`%.

## For Figure 3

@fig-three is below.

```{r}
#| label: fig-three
#| echo: false
#| message: false
#| warning: false
#| fig-align: center
#| fig-cap: Cost of the Area B Policy
#| fig-height: 5
#| fig-width: 5
#| out-width: 80%

data %>%
  dplyr::filter(target == 1) %>%
  mutate(area_b_cost_fact = fct_rev(area_b_cost_fact)) %>% # Reorder them
  ggplot() + 
  aes(area_b_cost_fact) +
  geom_bar(aes(y = after_stat(count / sum(count) )), # Make % 
    fill = "#852525",
    position = "dodge",
    width = 0.7,
    alpha = 0.8
  ) + 
  coord_flip() +
  labs(
    x = "",
    y = ""  ) +
  scale_y_continuous(, labels = scales::label_percent()) +
  theme_minimal() 
```
